// store/data.js

export const awards = [
  {
    name: "Cybertruck Elongation EVO",
    type: "Tesla",
    project: "FULL CARBON",
    label: "ORDER NOW!",
    youtubeId: "ipt3t7WWBR0",
    slug: "cybertruck-elongation-evo",
  },
  {
    name: "2025 M5 M",
    type: "BMW",
    project: "Performance",
    label: "ORDER NOW!",
    youtubeId: "4xzNldsfKeM",
    slug: "2025-m5-m",
  },
  {
    name: "2025 Panamera GTS",
    type: "Porsche",
    project: "ROCARS",
    label: "ORDER NOW!",
    youtubeId: "OREbZbvR9oU",
    slug: "2025-panamera-gts",
  },
  {
    name: "2024 Urus Performante",
    type: "Lamborghini",
    project: "Full Carbon by TopCar Design",
    label: "ORDER NOW!",
    youtubeId: "fZkFVYTB0Yg",
    slug: "2024-urus-performante",
  },
  {
    name: "2024 Phantom EWB",
    type: "Rolls-Royce",
    project: "Diamond Edition",
    label: "ORDER NOW!",
    youtubeId: "iO65hYAOVWU",
    slug: "2024-phantom-ewb",
  },
  {
    name: "2024 Purosangue",
    type: "Ferrari",
    project: "ROCARS",
    label: "ORDER NOW!",
    youtubeId: "DmOneaEHYvQ",
    slug: "2024-purosangue",
  },
  {
    name: "2024 XM",
    type: "BMW",
    project: "by Renegade Design",
    label: "ORDER NOW!",
    youtubeId: "xmOSb5SbRZ8",
    slug: "2024-xm-renegade",
  },
  {
    name: "2024 Spectre",
    type: "Rolls Royce",
    project: "by MANSORY",
    label: "ORDER NOW!",
    youtubeId: "LyAw0NKMYas",
    slug: "2024-spectre",
  },
  {
    name: "2024 CLE 53 Coupe",
    type: "Mercedes-AMG",
    project: "ROCARS",
    label: "ORDER NOW!",
    youtubeId: "RYHoyBhcA_A",
    slug: "2024-cle-53-coupe",
  },
  {
    name: "2024 Escalade V Long",
    type: "Cadillac",
    project: "by Larte Design",
    label: "ORDER NOW!",
    youtubeId: "FZvFkcgywEE",
    slug: "2024-escalade-v-long",
  },
  {
    name: "2024 S 63 E PERFORMANCE",
    type: "Mercedes-AMG",
    project: "by MANSORY",
    label: "ORDER NOW!",
    youtubeId: "Eser7F1bLkw",
    slug: "2024-s63-e-performance",
  },
  {
    name: "2024 Tiguan R-Line",
    type: "Volkswagen",
    project: "ROCARS",
    label: "ORDER NOW!",
    youtubeId: "9p8v_4FdwVQ",
    slug: "2024-tiguan-r-line",
  },
  {
    name: "2024 SV Long",
    type: "Range Rover",
    project: "MANSORY",
    label: "ORDER NOW!",
    youtubeId: "eHEHPdG0g6Y",
    slug: "2024-sv-long",
  },
  {
    name: "2024 Continental GT",
    type: "Bentley",
    project: "Azure",
    label: "ORDER NOW!",
    youtubeId: "feV3772d20I",
    slug: "2024-continental-gt",
  }
];